all: PRJBLD CTRLBLD PRJADDFS CSTADDFS
	./builddb

PRJBLD: PRJBLD.COB
	cobc -Wall -fixed -t PRJBLD.LIS -x PRJBLD.COB

PRJADDFS: PRJADDFS.COB SCPRJADD.COB PRJFD.COB PRJSELCT.COB
	cobc -Wall -fixed -t PRJADDFS.LIS -x PRJADDFS.COB

CTRLBLD: CTRLBLD.COB CTRLFD.COB CTRLSLCT.COB
	cobc -Wall -fixed -t CTRLBLD.LIS -x CTRLBLD.COB

CSTADDFS: CSTADDFS.COB SCCSTADD.COB CUSTFD.COB CTRLFD.COB CTRLSLCT.COB CUSTSLCT.COB
	cobc -Wall -fixed -t CSTADDFS.LIS -x CSTADDFS.COB

clean:
	rm -f *.LIS
	rm -f PRJBUILD
	rm -f PRJADDFS
	rm -f CSTADDFS
	rm -f CTRLBLD
	rm -f PRJBLD
	rm -f PROJECTS
	rm -f CUSTOMER
	rm -f CONTROL
